version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/uptime-kuma

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: